// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ActivateHost(arg1:string):Promise<string>;

export function AddHost(arg1:string):Promise<string>;

export function AgentLog(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function ApplyDNSMode():Promise<string>;

export function ApplyPreset(arg1:string):Promise<string>;

export function Autostart():Promise<boolean>;

export function CancelJob():Promise<void>;

export function Check():Promise<main.Snapshot>;

export function Hosts():Promise<Array<string>>;

export function LogError(arg1:string,arg2:string):Promise<void>;

export function Install():Promise<string>;

export function InstalledStrategy():Promise<Array<string>>;

export function Load():Promise<main.Snapshot>;

export function Options():Promise<main.OptionsView>;

export function PinDNS():Promise<string>;

export function Quit():Promise<void>;

export function Refresh():Promise<string>;

export function Remove():Promise<string>;

export function RemoveHost(arg1:string):Promise<string>;

export function SaveOptions(arg1:string,arg2:boolean,arg3:string):Promise<string>;

export function SetAutostart(arg1:boolean):Promise<string>;

export function SetScope(arg1:boolean):Promise<string>;

export function ShowWindow():Promise<void>;

export function TestOne(arg1:string):Promise<main.Snapshot>;

export function UnpinDNS():Promise<string>;
