// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateHost(arg1) {
  return window['go']['main']['App']['ActivateHost'](arg1);
}

export function AddHost(arg1) {
  return window['go']['main']['App']['AddHost'](arg1);
}

export function AgentLog(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AgentLog'](arg1, arg2, arg3, arg4);
}

export function ApplyDNSMode() {
  return window['go']['main']['App']['ApplyDNSMode']();
}

export function ApplyPreset(arg1) {
  return window['go']['main']['App']['ApplyPreset'](arg1);
}

export function Autostart() {
  return window['go']['main']['App']['Autostart']();
}

export function CancelJob() {
  return window['go']['main']['App']['CancelJob']();
}

export function Check() {
  return window['go']['main']['App']['Check']();
}

export function Hosts() {
  return window['go']['main']['App']['Hosts']();
}

export function LogError(arg1, arg2) {
  return window['go']['main']['App']['LogError'](arg1, arg2);
}

export function Install() {
  return window['go']['main']['App']['Install']();
}

export function InstalledStrategy() {
  return window['go']['main']['App']['InstalledStrategy']();
}

export function Load() {
  return window['go']['main']['App']['Load']();
}

export function Options() {
  return window['go']['main']['App']['Options']();
}

export function PinDNS() {
  return window['go']['main']['App']['PinDNS']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function Refresh() {
  return window['go']['main']['App']['Refresh']();
}

export function Remove() {
  return window['go']['main']['App']['Remove']();
}

export function RemoveHost(arg1) {
  return window['go']['main']['App']['RemoveHost'](arg1);
}

export function SaveOptions(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveOptions'](arg1, arg2, arg3);
}

export function SetAutostart(arg1) {
  return window['go']['main']['App']['SetAutostart'](arg1);
}

export function SetScope(arg1) {
  return window['go']['main']['App']['SetScope'](arg1);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function TestOne(arg1) {
  return window['go']['main']['App']['TestOne'](arg1);
}

export function Start() {
  return window['go']['main']['App']['Start']();
}

export function Stop() {
  return window['go']['main']['App']['Stop']();
}

export function UnpinDNS() {
  return window['go']['main']['App']['UnpinDNS']();
}
